### ISSUE TITLE
As a user I want to be able to add cards to a box.

### ISSUE THREAD

**Issue by patrickhaemmerle** [patrickhaemmerle/lerni#18]
The cards should have a front and a back side where I can enter an arbitrary text.

Editing and deleting cards is for later.
# Tasks
- [x] Create Card model
- [x] Implement AddCardToBoxAction
- [x] Implement a page "add a card to a box"
- [x] Add a link to the box in the boxes list to the "add a card to a box" page
- [x] Implement ListCardsForBoxQuery
- [x] Implement a page "list all cards for a box"
